services:
  cli:
    container_name: ${PROJECT_NAME}-cli
    build: cli/${PHP_VERSION}
    volumes:
      - ${SRC_PATH}:/workspace
  nginx:
    container_name: ${PROJECT_NAME}-nginx
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SRC_PATH}:/workspace
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm
    networks:
      - devnet

  fpm:
    container_name: ${PROJECT_NAME}-fpm  
    build: fpm/${PHP_VERSION}
    volumes:
      - ${SRC_PATH}:/workspace
    networks:
      - devnet

  # mysql:
  #   container_name: ${PROJECT_NAME}-mysql
  #   image: mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: devdb
  #     MYSQL_USER: devuser
  #     MYSQL_PASSWORD: devpass
  #   volumes:
  #     - dev-mysql-data:/var/lib/mysql
  #   networks:
  #     - devnet

  mssql:
    container_name: ${PROJECT_NAME}-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "p4ssword.Admin"
    ports:
      - 1433:1433
    volumes:
      - dev-mssql-data:/var/opt/mssql
    networks:
      - devnet

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  # dev-mysql-data:
    # external: true
  dev-mssql-data:
    external: true # Comment this line if you want to create a new volume; i prefer put all of my dev db data of the same DBM in one volume

networks:
  devnet:
